#include <iostream>

using namespace std;

int main()
{
    int a,b,c;
    cin>>a>>b;
    
    c = a + b;
    cout<<"the addition of value is:"<<c<<endl;
    
    c = a - b;
    cout<<"the substraction of value is:"<<c<<endl;
    
    c = a * b;
    cout<<"the multiplication of value is:"<<c<<endl;

    c = a / b;
    cout<<"the division of value is:"<<c<<endl;

    return 0;
}




